import 'package:flutter/material.dart';
import 'package:med_ai/screens/HomeScreen.dart';

class InstructionPage extends StatefulWidget {
  const InstructionPage({super.key});

  @override
  State<InstructionPage> createState() => _InstructionPageState();
}

class _InstructionPageState extends State<InstructionPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        children: [
          Padding(
            padding: EdgeInsets.only(top: 80, left: 20, right: 20, bottom: 80),
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    margin: EdgeInsets.only(
                      bottom: 20,
                    ),
                    child: Text(
                      "Welcome to\nMed AI",
                      style: TextStyle(
                          fontFamily: 'SofiaPro',
                          fontSize: 30,
                          color: Colors.white),
                    ),
                  ),
                  SizedBox(
                    height: 30,
                  ),
                  Text(
                    "Getting Started",
                    style: TextStyle(
                        fontFamily: 'SofiaPro',
                        fontSize: 20,
                        color: Color(0xFFFFB13D)),
                  ),
                  SizedBox(height: 10),
                  Text(
                    "1. Upload Your Report\n"
                    "- Click on the \"Image\" button icon.\n"
                    "- Select your report file in .png/jpeg format.\n"
                    "- Wait for the upload to complete.\n",
                    style: TextStyle(
                        fontFamily: 'SofiaPro',
                        fontSize: 16,
                        color: Colors.white),
                  ),
                  Text(
                    "2. Analyze the Report\n"
                    "- The AI will process the report and generate an analysis.\n",
                    style: TextStyle(
                        fontFamily: 'SofiaPro',
                        fontSize: 16,
                        color: Colors.white),
                  ),
                  Text(
                    "3. View Results\n"
                    "- The analysis results will be displayed on the screen.\n"
                    "- You can view detailed insights and summaries generated by the AI.\n",
                    style: TextStyle(
                        fontFamily: 'SofiaPro',
                        fontSize: 16,
                        color: Colors.white),
                  ),
                  SizedBox(height: 20),
                  Text(
                    "Tips for Best Results",
                    style: TextStyle(
                        fontFamily: 'SofiaPro',
                        fontSize: 20,
                        color: Color(0xFFFFB13D)),
                  ),
                  SizedBox(height: 10),
                  Text(
                    "- Ensure your report is clear and well-structured for optimal analysis.\n"
                    "- Use standard formatting and avoid extensive use of non-text elements.\n"
                    "- If the AI analysis seems off, try rephrasing or simplifying complex sections in your report.\n",
                    style: TextStyle(
                        fontFamily: 'SofiaPro',
                        fontSize: 16,
                        color: Colors.white),
                  ),
                  SizedBox(height: 20),
                  Text(
                    "Note:",
                    style: TextStyle(
                        fontFamily: 'SofiaPro',
                        fontSize: 20,
                        color: Color(0xFFFFB13D)),
                  ),
                  SizedBox(height: 10),
                  Text(
                    "Sometimes, the AI-generated responses might contain errors or inaccuracies. "
                    "Always review the analysis results and use your judgment to verify the information provided.",
                    style: TextStyle(
                        fontFamily: 'SofiaPro',
                        fontSize: 16,
                        color: Colors.white),
                  ),
                ],
              ),
            ),
          ),
          Positioned(
            bottom: 20,
            left: 20,
            right: 20,
            child: Container(
              height: 50,
              width: MediaQuery.of(context).size.width * 0.9,
              child: ElevatedButton(
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                ),
                onPressed: () {
                  Navigator.of(context).pushAndRemoveUntil(
                    MaterialPageRoute(builder: (context) => HomePage()),
                    (Route<dynamic> route) => false,
                  );
                },
                child: Text(
                  'Get Started',
                  style: TextStyle(
                    fontFamily: 'SofiaPro',
                    fontWeight: FontWeight.bold,
                    color: Colors.black,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
